# Generated by Django 4.2.6 on 2023-10-11 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.CharField(choices=[('Genre', 'genre'), ('Fantasy', 'fantasy'), ('Detective', 'detective')], default=('Genre', 'genre'), max_length=100, null=True),
        ),
    ]
