# Generated by Django 4.2.6 on 2023-10-24 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_remove_book_author_book_video_alter_book_genre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(choices=[('Genre', 'Genre'), ('Fantasy', 'Fantasy'), ('Detective', 'Detective'), ('Action', 'Action'), ('Adventure', 'Adventure'), ('Documentary', 'Documentary')], default=('Genre', 'Genre'), max_length=100, null=True),
        ),
    ]
